
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            legacy2012:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_legacy2012%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        default_entity_manager:       default
        auto_generate_proxy_classes: %kernel.debug%
       #auto_mapping: true
                
        entity_managers:
          
            default:
                connection: default
                mappings:

            legacy2012:
               connection: legacy2012
               mappings:
                    CeradLegacy2012Bundle: ~
                       