
cerad_zayso_index:
  path: /
  defaults:  { _controller: CeradZaysoBundle:Main:welcome }
  
cerad_zayso_welcome:
  path: /welcome
  defaults:  { _controller: CeradZaysoBundle:Main:welcome }
  
cerad_zayso_contact:
  path: /contact
  defaults:  { _controller: CeradZaysoBundle:Main:contact }
  
cerad_zayso_classes:
  path: /classes
  defaults:  { _controller: CeradZaysoBundle:Main:classes }
  
cerad_zayso_text_alerts:
  path: /text-alerts
  defaults:  { _controller: CeradZaysoBundle:Main:textAlerts }
  
cerad_zayso_schedules:
  path: /schedules
  defaults:  { _controller: CeradZaysoBundle:Main:schedules }
  
cerad_zayso_volunteer_plan:
  path: /volunteer/plan
  defaults:  { _controller: CeradZaysoBundle:Main:volunteerPlan }
  
cerad_zayso_volunteer_plan_form:
  path: /volunteer/plan/form
  defaults:  { _controller: CeradZaysoBundle:Main:volunteerPlanForm }
  
cerad_zayso_schedule:
  path: /schedule
  defaults:  { _controller: CeradZaysoBundle:Main:schedule }
  
cerad_zayso_schedule_my:
  path: /schedule/my
  defaults:  { _controller: CeradZaysoBundle:Main:schedule }
  
cerad_zayso_schedule_team:
  path: /schedule/team
  defaults:  { _controller: CeradZaysoBundle:Main:schedule }
  
cerad_zayso_schedule_referee:
  path: /schedule/referee
  defaults:  { _controller: CeradZaysoBundle:Main:schedule }
  
cerad_zayso_schedule_volunteer:
  path: /schedule/volunteer
  defaults:  { _controller: CeradZaysoBundle:Main:schedule }

cerad_zayso_results:
  path: /results
  defaults:  { _controller: CeradZaysoBundle:Main:results }
  
cerad_zayso_results_soccerfest:
  path: /results/soccerfest
  defaults:  { _controller: CeradZaysoBundle:Main:results }
  
cerad_zayso_results_poolplay:
  path: /results/pool-play
  defaults:  { _controller: CeradZaysoBundle:Main:results }
  
cerad_zayso_results_playoffs:
  path: /results/playoffs
  defaults:  { _controller: CeradZaysoBundle:Main:results }
  
cerad_zayso_results_tournament:
  path: /results/tournament
  defaults:  { _controller: CeradZaysoBundle:Main:results }
  
cerad_zayso_results_sportsmanship:
  path: /results/sportsmanship
  defaults:  { _controller: CeradZaysoBundle:Main:results }

# ==============================
# Admin stuff
cerad_zayso_admin:
  path: /admin
  defaults:  { _controller: CeradZaysoBundle:Main:admin }
  
# ====================================================
# Signing in stuff
cerad_zayso_signin:
    pattern:  /signin
    defaults: { _controller: CeradZaysoBundle:Security:signin }
    
cerad_zayso_signin_form:
    pattern:  /signin/form
    defaults: { _controller: CeradZaysoBundle:Security:signinForm }
    
cerad_zayso_signin_check:
    pattern:  /signin-check
    
cerad_zayso_signout:
    pattern:  /signout  
    
cerad_zayso_home:
    pattern:  /home  
    defaults:  { _controller: CeradZaysoBundle:Main:home }
    
cerad_zayso_user_header:
    pattern:  /user/header
    defaults: { _controller: CeradZaysoBundle:Main:userHeader }
   

